### ISSUE TITLE
Reflection is fitted to the plane incorrectly if main camera FOV is different than 75

### ISSUE THREAD

**Issue by coobenguy** [RisingThumb/gd_planar_reflection#1]
Title. 

At 75:
![image](https://github.com/RisingThumb/gd_planar_reflection/assets/76452238/51b3b3be-8178-4da3-8ec7-0cbcfe09d239)

Different than 75:
![image](https://github.com/RisingThumb/gd_planar_reflection/assets/76452238/971730cc-870a-48d0-97be-e214683a7e01)

**Comment by RisingThumb** [comment]
Hey @coobenguy thanks for reporting this! I was able to reproduce this, and fixed this in 80b050d3d541691811c894c89fe77ec2e3e68be0 . Additionally fixed an issue with the environment and camera settings of the main camera not being used.

If you get the chance to test this out, let me know if this fixes your issue, cheers!

**Comment by coobenguy** [comment]
Works perfectly, thanks! I wish I had realized the fix was so easy, I spent a long time yesterday overthinking it thinking it was something with the reflection math. Anyway Ill close the issue haha
